-- vim.g.barbar_auto_setup = false 
-- 
-- require'barbar'.setup {
--   animation = false,
--   auto_hide = false,
--   insert_at_end = true,
--   icons = {
--     separator = {left = '', right = ''},
--   },
-- }

-- vim.opt.termguicolors = true
-- require("bufferline").setup{}
